### ISSUE TITLE
Не запускается на Windows

### ISSUE THREAD

**Issue by talifa** [akella/jetro#1]
При попытке запуска проекта выдает ошибки и не запускается. Подскажи пожалуйста что я делаю не так.
```
C:\Users\Т\Desktop\jetro>npm i

> node-sass@3.13.1 install C:\Users\Т\Desktop\jetro\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\Т\Desktop\jetro\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Т\Desktop\jetro\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Т\\Desktop\\jetro\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.12.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Т\\Desktop\\jetro\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Т\\Desktop\\jetro\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Т\Desktop\jetro\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Т\Desktop\jetro\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Т\\Desktop\\jetro\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Т\\Desktop\\jetro\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Т\\Desktop\\jetro\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Т\Desktop\jetro\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Т\Desktop\jetro\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Т\Desktop\jetro\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Т\\Desktop\\jetro\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Т\Desktop\jetro\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-import@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-react@^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint-plugin-import@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN jetro@0.1.1 No repository field.
npm WARN jetro@0.1.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Т\AppData\Roaming\npm-cache\_logs\2018-12-22T20_37_02_136Z-debug.log
```

**Comment by akella** [comment]
npm i gulp-sass@latest --save-dev

**Comment by talifa** [comment]
спасибо!
